// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStock(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddStock'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddType(arg1) {
  return window['go']['main']['App']['AddType'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteStock(arg1) {
  return window['go']['main']['App']['DeleteStock'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetRecentBuy(arg1) {
  return window['go']['main']['App']['GetRecentBuy'](arg1);
}

export function GetRecentSell(arg1) {
  return window['go']['main']['App']['GetRecentSell'](arg1);
}

export function GetStock() {
  return window['go']['main']['App']['GetStock']();
}

export function GetType() {
  return window['go']['main']['App']['GetType']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}
