// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddType(arg1) {
  return window['go']['main']['App']['AddType'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetStock() {
  return window['go']['main']['App']['GetStock']();
}

export function GetType() {
  return window['go']['main']['App']['GetType']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}
